# Generated by Django 3.0.8 on 2020-09-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200917_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='toys',
            field=models.ManyToManyField(to='main_app.Toy'),
        ),
    ]
